---
- name: Prepare all Kubernetes nodes
  hosts: all
  become: yes
  roles:
    - common
    - crio
    - kubeadm
  tasks:
    - name: baseline playbook executed
      copy:
        content: "baseline_executed"
        dest: /tmp/ansible_baseline_executed

