name: Kubernetes Platform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

      run_kubeadm:
        description: "Run kubeadm ONLY first time"
        required: true
        default: "NO"

jobs:
  terraform:
    name: Terraform Lifecycle
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: k8s-nodes/terraform
        run: terraform init

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: k8s-nodes/terraform
        run: terraform destroy -auto-approve

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: k8s-nodes/terraform
        run: terraform apply -auto-approve

  ansible_baseline:
    name: Baseline OS Setup
    needs: terraform
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Initial wait after Terraform
        run: sleep 30

      - name: Validate Ansible inventory
        run: |
          ansible-inventory -i ansible/inventory/hosts.ini --list

      - name: Wait for SSH
        run: |
          ansible all -i ansible/inventory/hosts.ini \
          -m wait_for_connection \
          -a "timeout=300 delay=10"

      - name: Run baseline playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/site.yml

  kubeadm:
    name: Kubernetes Bootstrap
    needs: ansible_baseline
    if: github.event.inputs.run_kubeadm == 'YES'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/kubeadm.yml

  post_k8s:
    name: Post Kubernetes Setup
    needs: kubeadm
    if: github.event.inputs.run_kubeadm == 'YES'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/post-k8s.yml

