name: Kubernetes Platform Pipeline

on:
  workflow_dispatch:
    inputs:
      run_kubeadm:
        description: "Run kubeadm ONLY first time (YES / NO)"
        required: true
        default: "NO"

jobs:
  terraform:
    name: Terraform Provision
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Init & Apply
        working-directory: k8s-nodes/terraform
        run: |
          terraform init
          terraform apply -var-file=terraform.tfvars -auto-approve

  ansible_baseline:
    name: Baseline OS Setup
    needs: terraform
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Wait for SSH
        run: |
          ansible all -i ansible/inventory/hosts.ini \
          -m wait_for_connection \
          -a "timeout=300 delay=10"

      - name: Run baseline playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/site.yml

  kubeadm:
    name: Kubernetes Bootstrap
    needs: ansible_baseline
    if: github.event.inputs.run_kubeadm == 'YES'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/kubeadm.yml

  post_k8s:
    name: Post Kubernetes Setup
    needs: kubeadm
    if: github.event.inputs.run_kubeadm == 'YES'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          ansible-playbook -i ansible/inventory/hosts.ini ansible/post_setup.yml

